### ISSUE TITLE
[BUG] Unable to search attributes containing underscore in the name

### ISSUE THREAD

**Issue by ggodlewski** [lldap/lldap#998]
**To Reproduce**

```
ldapsearch -x -b "ou=people,dc=example,dc=com" -H ldap://localhost:3890 -D cn=admin,ou=people,dc=example,dc=com -W "first_name=Grzegorz"
Enter LDAP Password: 
# extended LDIF
#
# LDAPv3
# base <ou=people,dc=example,dc=com> with scope subtree
# filter: first_name=Grzegorz
# requesting: ALL
#

ldap_search_ext: Bad search filter (-7)
```

Are underscores even allowed by RFC?

https://www.rfc-editor.org/rfc/rfc2251#section-4.1.4

**Comment by nitnelave** [comment]
No: "These names MUST begin with a letter, and only contain ASCII letters, digit characters and hyphens."

In the case of first_name, you can also look for firstName (iirc), because it has an alias.
Aliases for custom attributes are only partially implemented, and definitely not in the web UI. There are plans to surface them better in the UI as well.
